use_frameworks!
platform :ios, '9.0'

target 'JWLoadingHUD_Example' do
  pod 'JWLoadingHUD', :path => '../'
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'SVProgressHUD'

  target 'JWLoadingHUD_Tests' do
    inherit! :search_paths

    
  end
end
