use_frameworks!
platform :ios, '9.0'

target 'JWProgressHUD_Example' do
  pod 'JWProgressHUD', :path => '../'
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'SVProgressHUD'

  target 'JWProgressHUD_Tests' do
    inherit! :search_paths

    
  end
  
end
